baseURL = ""
title = "~ / cmdr2"
theme = "cmdr2-minimal"

[pagination]
  pagerSize = 15

[permalinks]
  [permalinks.page]
    posts = "/notes/:year/:month/:slug/"

[taxonomies]
  tag = "tags"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.atom]
    mediaType = "application/atom+xml"
    noUgly = true
    baseName = "atom"

[outputs]
  home = ["HTML", "atom"]

[params]
  github = "https://github.com/cmdr2"
  x = "https://x.com/cmdr2"
  discord = "#"
  discordAlert = "cmdr2 is the discord username"

relativeURLs = true
canonifyURLs = false

disableKinds = ["RSS"]
