name: Make Blog
on:
  push:
    branches: [gh-pages]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Blog from Markdown Files
        uses: kamranahmedse/github-pages-blog-action@v0.0.10
        with:
          branch: gh-pages
